### ISSUE TITLE
Would you provide the 'aokvqa_val_kb.pkl'?

### ISSUE THREAD

**Issue by imyunjeong** [abril4416/KGen_VQA#1]
Hi,

I am trying to run the code from the KGen_VQA repository, but I encountered an issue due to the missing 'aokvqa_val_kb.pkl' and 'a-okvqa-repre.pkl' files. The code requires these files to execute the following line:

`kb_info=load_pkl('aokvqa_val_kb.pkl')`
`total_repre=load_pkl('a-okvqa-repre.pkl')`

Would you please provide these necessary file?

**Comment by abril4416** [comment]
Hi, sorry for the late reply. 

I guess you are talking about the code in: https://github.com/abril4416/KGen_VQA/blob/main/src/kb-gen/knowledge-diversification.ipynb (cell 9 and cell 10 -- the numbers before cells)? The kb_info (aokvqa_val_kb.pkl) was the initialized knowledge and the total_repre ('a-okvqa-repre.pkl') is the clustering results of initialized knowledge, which you can generate with the code in the 15-th cell. 

The initialized knowledge of A-OKVQA has been attached: https://1drv.ms/u/c/63ba220af7dfe9c7/EVOMoEYcr79Kv2r0BQw-jhEBEhGwmL2Wul3prlhV_dEweQ?e=0XVyeW

Please feel free to let me know if any other questions.
